GAME_DATABASE_UPDATE_WS_MSG_TYPE = 'UpdateGameDatabase'
ENGINE_UPDATE_WS_MSG_TYPE = 'UpdateEngine'
ENGINE_TERMINATION_WS_MSG_TYPE = 'EngineTermination'
STARTING_ENGINE_PROGRESS_WS_MSG_TYPE = 'StartingEngineProgress'

DEFAULT_PORT = 8888


