# constants to get functions of the DLLs - PE format
DOS_HEADER_SIZE = 0x40
E_LFANEW_OFFSET = 0x3C
E_LFANEW_SIZE = 4
PE_HEADER_SIZE = 0x200
PE_SIGNATURE_SIZE = 4
VALID_PE_SIGNATURE = 0x00004550
OPTIONAL_HEADER_OFFSET = 0x18
OPTIONAL_HEADER_SIZE = 2
SYS32 = 0x10B
SYS64 = 0x20B
SYS32_DATA_DIR_OFFSET = 0x60
SYS64_DATA_DIR_OFFSET = 0x70
DATA_DIR_SIZE = 4
EXPORT_TABLE_SIZE = 40

NUM_OF_FUNC_OFFSET = 0x14
NUM_OF_FUNC_SIZE = 4
NUM_OF_NAME_OFFSET = 0x18
NUM_OF_NAME_SIZE = 4
FUNC_RVA_ARRAY_RAV_OFFSET = 0x1C
FUNC_RVA_ARRAY_RAV_SIZE = 4
FUNC_NAME_RVA_ARRAY_RAV_OFFSET = 0x20
FUNC_NAME_RVA_ARRAY_RAV_SIZE = 4
FUNC_ORDINAL_RVA_ARRAY_OFFSET = 0x24
FUNC_ORDINAL_RVA_ARRAY_SIZE = 4
MAX_NUM_OF_NAME = 4096
FUNC_NAME_SIZE = 256
FUNC_ORDINAL_SIZE = 2
FUNC_RVA_SIZE = 4
FUNC_NAME_RAV_ARRAY_ITEM_SIZE = 4


LITTLE_ENDIAN = 'little'
BIG_ENDIAN = 'big'
