# TYPE LIST
LIST_COUNT_OFFSET: int = 0X18
LIST_COUNT_LENGTH: int = 0X8
LIST_FIRST_ITEM_OFFSET: int = 0X20

## GENERIC LIST
GENERIC_LIST_ITEM_COUNT_OFFSET: int = 0X18
GENERIC_LIST_ITEM_COUNT_LENGTH: int = 0X4
GENERIC_LIST_ITEM_LIST_OFFSET: int = 0X10

## GENERIC DICT
GENERIC_DICT_32BIT_HEADER_LENGTH: int = 0x8
GENERIC_DICT_64BIT_HEADER_LENGTH: int = 0x10
GENERIC_DICT_BUCKET_ADDR_LENGTH: int = 0x8
GENERIC_DICT_ENTRY_LIST_ADDR_LENGTH: int = 0x8
GENERIC_DICT_COUNT_LENGTH: int = 0x4
# offsets from entry list
GENERIC_DICT_ENTRY_LENGTH: int = 0x18  # every entry has 0x18-byte length
GENERIC_DICT_ENTRY_LIST_FIRST_ITEM_OFFSET: int = 0x20  # first entry offset
GENERIC_DICT_ENTRY_HASH_CODE_LENGTH: int = 0x4
GENERIC_DICT_ENTRY_NEXT_INDEX_LENGTH: int = 0x4
GENERIC_DICT_ENTRY_VALUE_LENGTH: int = 0x8
GENERIC_DICT_ENTRY_KEY_LENGTH: int = 0x8

# STRING
STRING_32BIT_HEADER_LENGTH = 0x8
STRING_64BIT_HEADER_LENGTH = 0x10
STRING_CHAR_COUNT_LENGTH = 0x4
